# Generated by Django 5.1.4 on 2025-01-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsaenc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encrypteddna',
            old_name='sequence',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='encrypteddna',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='encrypteddna',
            name='encrypted_data',
        ),
        migrations.RemoveField(
            model_name='encrypteddna',
            name='gen_description',
        ),
        migrations.RemoveField(
            model_name='encrypteddna',
            name='gene_name',
        ),
        migrations.RemoveField(
            model_name='encrypteddna',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='encrypteddna',
            name='encrypted_dna',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
