# Generated by Django 5.1.4 on 2025-01-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enc',
            new_name='Honey',
        ),
    ]
