# Generated by Django 5.1.4 on 2025-01-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0002_rename_enc_honey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honey',
            name='length',
        ),
    ]
