# Generated by Django 5.1.4 on 2025-01-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enc',
            name='encrypted_sequence',
            field=models.CharField(blank=True, null=True),
        ),
    ]
