# Generated by Django 5.1.4 on 2025-01-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enc',
            name='gc_content',
        ),
    ]
