# Generated by Django 5.1.4 on 2025-01-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enc', '0002_remove_enc_gc_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enc',
            name='length',
        ),
    ]
